### PR TITLE
Add two new methods

### PR DESCRIPTION
**Pull request by upwebdesign**
Add methods getAttendeePollAnswers and getSessionPolls

### CODE REVIEW

**Comment by slakbal** [comment]
wow you are fast 👍 :)

**Comment by upwebdesign** [comment]
haha, we need that functionality! :) Thanks for maintaining!

**Comment by upwebdesign** [comment]
Could you do me a favor and add a new release 1.0.1 so I can update the code in my projects? Sorry if I jumped the gun.

**Comment by slakbal** [comment]
Nope just needed a few more minutes, updated the way I build paths in the Webinar class to how you did it in the PR... I like it more. Thanks for that! The release should be available by now.

**Comment by slakbal** [comment]
ps. I brought back the way that I use the entity classes to enforce the data-structures and the required/default/optional fields on Webinar and Registrant back again. It just feels somehow robuster. Have a look at the code and the entity classes. If you have recommendations throw them may way :)

**Comment by slakbal** [comment]
And at some point, I probably need to write a couple of tests for this thing... yaawwwnnn :)

**Comment by upwebdesign** [comment]
Yeah, I've been running a lot of tests lately. Borrrring! I will have a peak at the code and make any recommendations that I see.

**Comment by upwebdesign** [comment]
Would be nice to be able to do something like this: 
GotoWebinar::webinar($webinarKey)->delete();
GotoWebinar::registrant($registrantKey)->update([]);

This is just a quick idea.

**Comment by upwebdesign** [comment]
One other thing I was thinking about, it would be nice to also return all responses from GTW were already in a Laravel Collection. Thoughts? So we can do something like this:
`$attendees = GotoWebinar::getAttendees($webinar->webinarKey, $webinar->sessionKey)`
`$attendee = $attendees->first();`
This could also be a config option in config.php
`'collections' => true`
or something similar
`'response_type' => 'collection' // or array or object`

**Comment by slakbal** [comment]
On this point:

GotoWebinar::webinar($webinarKey)->delete();
GotoWebinar::registrant($registrantKey)->update([]);

my first thought is that I like it also a lot but I think that it would require me to re-structure the code differently if I'm not mistaken e.g. fluent style in separate classes..? Will check back at this at a later stage or if you maybe have some examples to get me going quickly it would be nice. Time is bit tricky on my side just at the moment as I have to also finish work on the actual project that is consuming this package :)

I like the idea of the collections a lot. It would work on most of the responses but might be an issue on the account response which is a collated response of data and a pagination object. But I like the idea! Here the same I'll have to check back on it at a later stage or if you have some time somewhere throw a pull request my way.

Can I please ask you once you feel that the package is stable enough that you give me also a heads-up then I can start the abandoned process on the old package and start moving other users over. Would be interesting to hear what type of project you are using it with.

Thanks for your ideas, I enjoy that someone is using this and helping to make it better and feel free to throw some PR's over I learned quite a bit already from you ;)

**Comment by upwebdesign** [comment]
I agree that it is some work to refactor the code. At this point it works and I am grateful for this package. I would recommend keep going with this package as is until stable and you are good with the working code. Then you can consider refactoring and even make a major branch 2.0.0 or similar. I will be using this package in a live environment soon.

**Comment by slakbal** [comment]
Hey there @upwebdesign, things with this package stable on your side?

**Comment by upwebdesign** [comment]
We have not used the code in production as of yet, but working well in our local environment. Will keep you posted should we run into issues. Thanks!

**Pull request merged**
