### PR TITLE
Feature oauth v2 authorization code

### PR DESCRIPTION
**Pull request by wize-wiz**
Solves #12

### CODE REVIEW

**Review by valeksa — COMMENTED** [review]
Commands\GoToAuthorizeLinkCommand.php file is missing?

**Comment by wize-wiz** [comment]
@valeksa Aah that line can be removed, `GoToGenerateLinkCommand` used to be called `GoToAuthorizeLinkCommand`. I have mostly rewritten this entire package in a new repository anyway, this PR is quite thin compared of what it can do now.

**Comment by valeksa** [comment]
Hello,

I just want to say that I have tested on two clients and this PR works without problem,
with GOTO_LEGACY=true (old client Direct Login) and new client.

But according to README, to generate an authorization link we have to execute following command:
php artisan goto:authorize-link

but this command does not exist, so we have to generate authorization link by hand according to gotowebinar documentation.

On more thing, version of PHP should be 7.4. On 7.2 php artisan command can not be executed.

**Comment by wize-wiz** [comment]
@valeksa Which command can't be executed on 7.2?

**Pull request closed without merging**
