### PR TITLE
Add getSessionQuestions

### PR DESCRIPTION
**Pull request by upwebdesign**
I needed this method so I am contributing to this trait.

### CODE REVIEW

**Comment by upwebdesign** [comment]
@slakbal Let me know when you can get this merged in. We are planning on launching with your package early Jan, 2018. Thanks!

**Review by slakbal — APPROVED** [review]
All good

**Comment by slakbal** [comment]
@upwebdesign was out of office for a couple of days. Merging now.

**Comment by upwebdesign** [comment]
@slakbal thanks for merging that pull request in!

**Pull request merged**
